apiVersion: v1
kind: Service
metadata:
  name: policy-agent-webhook
  namespace: policy-agent
  labels:
    app: policy-agent-webhook
spec:
  type: ClusterIP
  ports:
    - name: webhook
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: policy-agent-webhook
