package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// HookType represents the type of Git hook
type HookType string

const (
	HookPreCommit  HookType = "pre-commit"
	HookPrePush    HookType = "pre-push"
	HookCommitMsg  HookType = "commit-msg"
)

// GitHooksManager manages Git hooks installation
type GitHooksManager struct {
	repoPath string
	hooksDir string
}

// NewGitHooksManager creates a new Git hooks manager
func NewGitHooksManager(repoPath string) (*GitHooksManager, error) {
	if repoPath == "" {
		// Try to find Git repository
		cwd, err := os.Getwd()
		if err != nil {
			return nil, fmt.Errorf("failed to get current directory: %w", err)
		}
		repoPath = cwd
	}

	// Find .git directory
	gitDir, err := findGitDir(repoPath)
	if err != nil {
		return nil, err
	}

	hooksDir := filepath.Join(gitDir, "hooks")

	return &GitHooksManager{
		repoPath: repoPath,
		hooksDir: hooksDir,
	}, nil
}

// Install installs Git hooks
func (m *GitHooksManager) Install(hooks []HookType) error {
	// Ensure hooks directory exists
	if err := os.MkdirAll(m.hooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	policyAgentPath, err := m.getPolicyAgentPath()
	if err != nil {
		return fmt.Errorf("failed to find policy-agent binary: %w", err)
	}

	for _, hookType := range hooks {
		if err := m.installHook(hookType, policyAgentPath); err != nil {
			return fmt.Errorf("failed to install %s hook: %w", hookType, err)
		}
		fmt.Printf("✅ Installed %s hook\n", hookType)
	}

	return nil
}

// Uninstall removes Git hooks
func (m *GitHooksManager) Uninstall(hooks []HookType) error {
	for _, hookType := range hooks {
		hookPath := filepath.Join(m.hooksDir, string(hookType))

		// Check if hook exists and was installed by policy-agent
		content, err := os.ReadFile(hookPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue // Hook doesn't exist
			}
			return fmt.Errorf("failed to read hook %s: %w", hookType, err)
		}

		if !strings.Contains(string(content), "policy-agent") {
			fmt.Printf("⚠️  Skipping %s (not installed by policy-agent)\n", hookType)
			continue
		}

		if err := os.Remove(hookPath); err != nil {
			return fmt.Errorf("failed to remove hook %s: %w", hookType, err)
		}

		fmt.Printf("✅ Removed %s hook\n", hookType)
	}

	return nil
}

// List lists installed hooks
func (m *GitHooksManager) List() (map[HookType]bool, error) {
	hooks := map[HookType]bool{
		HookPreCommit: false,
		HookPrePush:   false,
		HookCommitMsg: false,
	}

	for hookType := range hooks {
		hookPath := filepath.Join(m.hooksDir, string(hookType))

		content, err := os.ReadFile(hookPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("failed to read hook %s: %w", hookType, err)
		}

		// Check if installed by policy-agent
		if strings.Contains(string(content), "policy-agent") {
			hooks[hookType] = true
		}
	}

	return hooks, nil
}

// installHook installs a specific hook
func (m *GitHooksManager) installHook(hookType HookType, policyAgentPath string) error {
	hookPath := filepath.Join(m.hooksDir, string(hookType))

	// Check if hook already exists
	if _, err := os.Stat(hookPath); err == nil {
		// Hook exists - check if it's ours
		content, err := os.ReadFile(hookPath)
		if err != nil {
			return fmt.Errorf("failed to read existing hook: %w", err)
		}

		if strings.Contains(string(content), "policy-agent") {
			fmt.Printf("⚠️  %s hook already installed, updating...\n", hookType)
		} else {
			return fmt.Errorf("%s hook already exists (not installed by policy-agent). Remove it manually or use --force", hookType)
		}
	}

	// Generate hook script
	script := m.generateHookScript(hookType, policyAgentPath)

	// Write hook file
	if err := os.WriteFile(hookPath, []byte(script), 0755); err != nil {
		return fmt.Errorf("failed to write hook file: %w", err)
	}

	return nil
}

// generateHookScript generates the hook script content
func (m *GitHooksManager) generateHookScript(hookType HookType, policyAgentPath string) string {
	switch hookType {
	case HookPreCommit:
		return fmt.Sprintf(`#!/bin/sh
# policy-agent pre-commit hook
# Auto-generated by policy-agent - do not edit manually

echo "🔍 Running policy validation..."

# Get list of staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

if [ -z "$STAGED_FILES" ]; then
    echo "No files to validate"
    exit 0
fi

# Validate each staged file
EXIT_CODE=0
for FILE in $STAGED_FILES; do
    # Skip deleted files
    if [ ! -f "$FILE" ]; then
        continue
    fi

    # Determine if file is a configuration file
    case "$FILE" in
        *.yaml|*.yml|*.json|*.tf|*.hcl)
            echo "Validating: $FILE"
            %s validate --file "$FILE" --format text
            if [ $? -ne 0 ]; then
                EXIT_CODE=1
            fi
            ;;
    esac
done

if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ Policy validation failed. Fix violations or use --no-verify to skip."
    exit 1
fi

echo "✅ All checks passed!"
exit 0
`, policyAgentPath)

	case HookPrePush:
		return fmt.Sprintf(`#!/bin/sh
# policy-agent pre-push hook
# Auto-generated by policy-agent - do not edit manually

echo "🔍 Running policy validation before push..."

# Validate all tracked configuration files
CONFIG_FILES=$(git ls-files | grep -E '\.(yaml|yml|json|tf|hcl)$')

if [ -z "$CONFIG_FILES" ]; then
    echo "No configuration files to validate"
    exit 0
fi

EXIT_CODE=0
for FILE in $CONFIG_FILES; do
    if [ -f "$FILE" ]; then
        echo "Validating: $FILE"
        %s validate --file "$FILE" --format text
        if [ $? -ne 0 ]; then
            EXIT_CODE=1
        fi
    fi
done

if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ Policy validation failed. Fix violations or use --no-verify to skip."
    exit 1
fi

echo "✅ All checks passed!"
exit 0
`, policyAgentPath)

	case HookCommitMsg:
		return fmt.Sprintf(`#!/bin/sh
# policy-agent commit-msg hook
# Auto-generated by policy-agent - do not edit manually

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Check if commit message mentions policy violations being fixed
if echo "$COMMIT_MSG" | grep -qi "skip.*policy\|bypass.*policy"; then
    echo "⚠️  Warning: Commit message indicates policy bypass"
fi

exit 0
`, policyAgentPath)

	default:
		return ""
	}
}

// getPolicyAgentPath finds the policy-agent binary path
func (m *GitHooksManager) getPolicyAgentPath() (string, error) {
	// Try to find in PATH
	path, err := exec.LookPath("policy-agent")
	if err == nil {
		return path, nil
	}

	// Try common installation paths
	commonPaths := []string{
		"/usr/local/bin/policy-agent",
		"/usr/bin/policy-agent",
		filepath.Join(os.Getenv("HOME"), "bin", "policy-agent"),
		filepath.Join(os.Getenv("HOME"), ".local", "bin", "policy-agent"),
	}

	if runtime.GOOS == "windows" {
		commonPaths = append(commonPaths,
			filepath.Join(os.Getenv("PROGRAMFILES"), "policy-agent", "policy-agent.exe"),
			filepath.Join(os.Getenv("LOCALAPPDATA"), "policy-agent", "policy-agent.exe"),
		)
	}

	for _, p := range commonPaths {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
	}

	return "", fmt.Errorf("policy-agent binary not found in PATH or common locations")
}

// findGitDir finds the .git directory
func findGitDir(startPath string) (string, error) {
	current := startPath

	for {
		gitDir := filepath.Join(current, ".git")

		// Check if .git exists
		info, err := os.Stat(gitDir)
		if err == nil {
			if info.IsDir() {
				return gitDir, nil
			}
			// .git is a file (submodule or worktree)
			content, err := os.ReadFile(gitDir)
			if err != nil {
				return "", fmt.Errorf("failed to read .git file: %w", err)
			}
			// Parse gitdir: path
			lines := strings.Split(string(content), "\n")
			for _, line := range lines {
				if strings.HasPrefix(line, "gitdir:") {
					path := strings.TrimSpace(strings.TrimPrefix(line, "gitdir:"))
					if !filepath.IsAbs(path) {
						path = filepath.Join(current, path)
					}
					return path, nil
				}
			}
		}

		// Move up one directory
		parent := filepath.Dir(current)
		if parent == current {
			// Reached root
			return "", fmt.Errorf("not a git repository (or any of the parent directories)")
		}
		current = parent
	}
}
